Enable multiple meshes to have the same tree index
cognitedata/3d-web-parser pull request #26
Opened 2019-03-27 13:43 UTC by Verkhovskaya

This is valid according to @f2cognite. It first started being an issue with Christmas tree.

2019-03-27 14:18 UTC, anderscognite requested changes
\o/

2019-03-27 14:18 UTC, anderscognite commented on src/customFileParser/loadSectorMetadata.ts
> +  if (magicBytes !== 1178874697) {
Maybe store the number in the variable (so we don't get out of sync message)?

2019-03-27 14:18 UTC, anderscognite commented on src/geometry/InstancedMeshGroup.ts
> +const tempBox = new THREE.Box3();
Call it globalBox (same pattern as many other places)?

2019-03-27 14:18 UTC, anderscognite commented on src/geometry/MergedMeshGroup.ts
> +const tempBox = new THREE.Box3();
`globalBox`

2019-03-27 14:20 UTC, f2cognite commented on src/customFileParser/loadSectorMetadata.ts
> +  if (magicBytes !== 1178874697) {
Also maybe store as hex? `0x46443349` (that makes it more clear what the magic bytes actually are)

2019-03-27 14:21 UTC, Verkhovskaya commented on src/customFileParser/loadSectorMetadata.ts
> +  if (magicBytes !== 1178874697) {
Oh yeah, so, uh, what *are* the magic bytes?

2019-03-27 14:23 UTC, Verkhovskaya commented on src/geometry/MergedMeshGroup.ts
> +const tempBox = new THREE.Box3();
Done

2019-03-27 14:24 UTC, Verkhovskaya commented on src/customFileParser/loadSectorMetadata.ts
> +  if (magicBytes !== 1178874697) {
And done.

2019-03-27 14:25 UTC, f2cognite commented on src/customFileParser/loadSectorMetadata.ts
> +  if (magicBytes !== 1178874697) {
The magic bytes are literally `I3DF` (`49 33 44 46`, reverse order as 32-bit integer since it's little-endian)

2019-03-27 14:34 UTC, anderscognite requested changes
Almost there!

2019-03-27 14:34 UTC, anderscognite commented on src/customFileParser/loadSectorMetadata.ts
> +    throw Error('Start of sector file is incorrect. Expected 0x46443349, got ' + magicBytes.toString(16));
Still hard coded in the message... :P

2019-03-27 14:57 UTC, Verkhovskaya commented on src/customFileParser/loadSectorMetadata.ts
> +    throw Error('Start of sector file is incorrect. Expected 0x46443349, got ' + magicBytes.toString(16));
... Oops

2019-03-28 05:19 UTC, anderscognite approved these changes
Nice!

2019-03-28 11:51 UTC, merged